# Generated by Django 4.1.1 on 2022-09-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='catagory',
            new_name='category',
        ),
    ]
